In [ ]:

import numpy as np
import polars as pl

from autotsc.models import AutoTSCModel
from autotsc.utils import load_dataset

In [ ]:
X_train, y_train, X_test, y_test = load_dataset("Computers")
# X_train, y_train, X_test, y_test = load_dataset("ArrowHead")
# X_train, y_train, X_test, y_test = load_dataset("Ham")

model = AutoTSCModel(verbose=1, n_jobs=-1)
model.fit(X_train, y_train)

2025-11-15 12:04:26,451	INFO worker.py:2012 -- Started a local Ray instance.
/home/gasper_p/workspace/repos/AutoTSC/.venv/lib/python3.12/site-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

|------------------------|
| Number of samples: 250 |
| Number of channels: 1  |
| Length of series: 720  |
| Number of classes: 2   |
| CPUs: 24/24            |
| GPUs: 2/2              |
|------------------------|

(train_fold pid=2608362) 2025-11-15 12:04:31.051299: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(train_fold pid=2608362) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model 0 fitted, accuracy: 0.8360, time: 0.26s
Model 2 fitted, accuracy: 0.4880, time: 0.00s
Model 3 fitted, accuracy: 0.5240, time: 0.07s
Model 1 fitted, accuracy: 0.8160, time: 0.12s
Model 4 fitted, accuracy: 0.7680, time: 0.19s
Model 5 fitted, accuracy: 0.6360, time: 0.12s
Model 6 fitted, accuracy: 0.8440, time: 0.18s
Model 7 fitted, accuracy: 0.7920, time: 0.09s
Model 8 fitted, accuracy: 0.8440, time: 0.21s
Model 9 fitted, accuracy: 0.7920, time: 0.08s
Model 11 fitted, accuracy: 0.7800, time: 0.08s
Model 10 fitted, accuracy: 0.8160, time: 0.22s
Model 12 fitted, accuracy: 0.8320, time: 0.19s
Model 13 fitted, accuracy: 0.8040, time: 0.09s
Model 15 fitted, accuracy: 0.8320, time: 0.06s
Model 14 fitted, accuracy: 0.8320, time: 0.23s
Model 17 fitted, accuracy: 0.7680, time: 0.09s
Model 16 fitted, accuracy: 0.8320, time: 0.23s
Model 18 fitted, accuracy: 0.7280, time: 0.18s
Model 20 fitted, accuracy: 0.8240, time: 0.07s
Model 19 fitted, accuracy: 0.8080, time: 0.20s
Model 21 fitted, accuracy: 0.7840, time: 0.55s
Model 22 fitted, accuracy: 0.8320, time: 0.47s
Model 24 fitted, accuracy: 0.7240, time: 0.15s
Model 25 fitted, accuracy: 0.8160, time: 0.12s
Model 23 fitted, accuracy: 0.8680, time: 1.25s
Model 26 fitted, accuracy: 0.7520, time: 0.08s
Model 28 fitted, accuracy: 0.6280, time: 0.11s
Model 27 fitted, accuracy: 0.7600, time: 0.38s
Model 29 fitted, accuracy: 0.6120, time: 0.12s
Model 30 fitted, accuracy: 0.8600, time: 2.63s
Model 31 fitted, accuracy: 0.8560, time: 2.46s

(pid=gcs_server) [2025-11-15 12:04:55,046 E 2608120 2608120] (gcs_server) gcs_server.cc:302: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_fold pid=2608359) 2025-11-15 12:04:31.051299: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. [repeated 5x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(train_fold pid=2608359) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. [repeated 5x across cluster]

Model 32 fitted, accuracy: 0.8560, time: 2.33s

(raylet) [2025-11-15 12:04:56,373 E 2608273 2608273] (raylet) main.cc:975: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_fold pid=2608360) [2025-11-15 12:04:58,404 E 2608360 2608565] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-15 12:04:58,826 E 2608025 2608356] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Model 33 fitted, accuracy: 0.8320, time: 3.25s

(train_fold pid=2608374) [2025-11-15 12:04:58,414 E 2608374 2608720] core_worker_process.cc:825: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14 [repeated 5x across cluster]

AutoTSCModel2(verbose=1)

In [6]:
summary = model.summary()
summary

shape: (38, 8)
┌───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ model_id  ┆ classifier ┆ fold_predi ┆ fold_proba ┆ true_labe ┆ validatio ┆ training_ ┆ stacking_ │
│ ---       ┆ ---        ┆ ctions     ┆ bilities   ┆ ls        ┆ n_accurac ┆ time_seco ┆ level     │
│ str       ┆ str        ┆ ---        ┆ ---        ┆ ---       ┆ y         ┆ nds       ┆ ---       │
│           ┆            ┆ list[str]  ┆ list[list[ ┆ list[str] ┆ ---       ┆ ---       ┆ i64       │
│           ┆            ┆            ┆ f64]]      ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2         ┆ DummyClass ┆ ["1", "1", ┆ [[0.5,     ┆ ["1",     ┆ 0.488     ┆ 0.000692  ┆ 0         │
│           ┆ ifier()    ┆ … "1"]     ┆ 0.5],      ┆ "1", …    ┆           ┆           ┆           │
│           ┆            ┆            ┆ [0.5,      ┆ "2"]      ┆           ┆           ┆           │
│           ┆            ┆            ┆ 0.5], …    ┆           ┆           ┆           ┆           │
│           ┆            ┆            ┆ [0.…       ┆           ┆           ┆           ┆           │
│ 3         ┆ SklearnCla ┆ ["2", "2", ┆ [[0.470094 ┆ ["1",     ┆ 0.524     ┆ 0.068764  ┆ 0         │
│           ┆ ssifierWra ┆ … "2"]     ┆ ,          ┆ "1", …    ┆           ┆           ┆           │
│           ┆ pper(class ┆            ┆ 0.529906], ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ [0.4140…   ┆           ┆           ┆           ┆           │
│ 29        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.149336 ┆ ["1",     ┆ 0.612     ┆ 0.118009  ┆ 0         │
│           ┆ ssifierWra ┆ … "1"]     ┆ ,          ┆ "1", …    ┆           ┆           ┆           │
│           ┆ pper(class ┆            ┆ 0.850664], ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ [0.4857…   ┆           ┆           ┆           ┆           │
│ 28        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1",     ┆ 0.628     ┆ 0.113674  ┆ 0         │
│           ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ "1", …    ┆           ┆           ┆           │
│           ┆ pper(class ┆            ┆ [0.48,     ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ 0.52], ……  ┆           ┆           ┆           ┆           │
│ 5         ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1",     ┆ 0.636     ┆ 0.11771   ┆ 0         │
│           ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ "1", …    ┆           ┆           ┆           │
│           ┆ pper(class ┆            ┆ [0.38,     ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ 0.62], ……  ┆           ┆           ┆           ┆           │
│ …         ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         │
│ rf        ┆ RandomFore ┆ ["2", "2", ┆ null       ┆ ["1",     ┆ 0.864     ┆ null      ┆ 1         │
│           ┆ stClassifi ┆ … "1"]     ┆            ┆ "1", …    ┆           ┆           ┆           │
│           ┆ er(n_estim ┆            ┆            ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ 23        ┆ QUANTClass ┆ ["1", "2", ┆ [[0.53,    ┆ ["1",     ┆ 0.868     ┆ 1.253702  ┆ 0         │
│           ┆ ifier(rand ┆ … "2"]     ┆ 0.47],     ┆ "1", …    ┆           ┆           ┆           │
│           ┆ om_state=1 ┆            ┆ [0.335,    ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆ 0.665],…   ┆           ┆           ┆           ┆           │
│ pca-ridge ┆ Pipeline(s ┆ ["2", "2", ┆ null       ┆ ["1",     ┆ 0.868     ┆ null      ┆ 1         │
│           ┆ teps=[('pc ┆ … "1"]     ┆            ┆ "1", …    ┆           ┆           ┆           │
│           ┆ a',PCA(n_c ┆            ┆            ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ hgb       ┆ HistGradie ┆ ["1", "2", ┆ null       ┆ ["1",     ┆ 0.876     ┆ null      ┆ 1         │
│           ┆ ntBoosting ┆ … "1"]     ┆            ┆ "1", …    ┆           ┆           ┆           │
│           ┆ Classifier ┆            ┆            ┆ "2"]      ┆           ┆           ┆           │
│           ┆ …          ┆            ┆            ┆           ┆           ┆           ┆           │
│ ridge     ┆ RidgeClass ┆ ["1", "2", ┆ null       ┆ ["1",     ┆ 0.888     ┆ null      ┆ 1         │
│           ┆ ifierCV()  ┆ … "1"]     ┆            ┆ "1", …    ┆           ┆           ┆           │
│           ┆            ┆            ┆            ┆ "2"]      ┆           ┆           ┆           │
└───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [10]:
summary_base = summary.filter(pl.col("stacking_level") == 0).sort("validation_accuracy")
summary_base

shape: (34, 8)
┌──────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ model_id ┆ classifier ┆ fold_predi ┆ fold_proba ┆ true_label ┆ validatio ┆ training_ ┆ stacking_ │
│ ---      ┆ ---        ┆ ctions     ┆ bilities   ┆ s          ┆ n_accurac ┆ time_seco ┆ level     │
│ str      ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ y         ┆ nds       ┆ ---       │
│          ┆            ┆ list[str]  ┆ list[list[ ┆ list[str]  ┆ ---       ┆ ---       ┆ i64       │
│          ┆            ┆            ┆ f64]]      ┆            ┆ f64       ┆ f64       ┆           │
╞══════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ DummyClass ┆ ["1", "1", ┆ [[0.5,     ┆ ["1", "1", ┆ 0.488     ┆ 0.000692  ┆ 0         │
│          ┆ ifier()    ┆ … "1"]     ┆ 0.5],      ┆ … "2"]     ┆           ┆           ┆           │
│          ┆            ┆            ┆ [0.5,      ┆            ┆           ┆           ┆           │
│          ┆            ┆            ┆ 0.5], …    ┆            ┆           ┆           ┆           │
│          ┆            ┆            ┆ [0.…       ┆            ┆           ┆           ┆           │
│ 3        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.470094 ┆ ["1", "1", ┆ 0.524     ┆ 0.068764  ┆ 0         │
│          ┆ ssifierWra ┆ … "2"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ 0.529906], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.4140…   ┆            ┆           ┆           ┆           │
│ 29       ┆ SklearnCla ┆ ["2", "2", ┆ [[0.149336 ┆ ["1", "1", ┆ 0.612     ┆ 0.118009  ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ 0.850664], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.4857…   ┆            ┆           ┆           ┆           │
│ 28       ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1", "1", ┆ 0.628     ┆ 0.113674  ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ [0.48,     ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.52], ……  ┆            ┆           ┆           ┆           │
│ 5        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1", "1", ┆ 0.636     ┆ 0.11771   ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ [0.38,     ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.62], ……  ┆            ┆           ┆           ┆           │
│ …        ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 8        ┆ MultiRocke ┆ ["2", "2", ┆ [[0.437161 ┆ ["1", "1", ┆ 0.844     ┆ 0.214048  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.562839], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3894…   ┆            ┆           ┆           ┆           │
│ 31       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.451551 ┆ ["1", "1", ┆ 0.856     ┆ 2.459973  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.548449], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3069…   ┆            ┆           ┆           ┆           │
│ 32       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.428505 ┆ ["1", "1", ┆ 0.856     ┆ 2.326782  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.571495], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3080…   ┆            ┆           ┆           ┆           │
│ 30       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.466823 ┆ ["1", "1", ┆ 0.86      ┆ 2.626712  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.533177], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3264…   ┆            ┆           ┆           ┆           │
│ 23       ┆ QUANTClass ┆ ["1", "2", ┆ [[0.53,    ┆ ["1", "1", ┆ 0.868     ┆ 1.253702  ┆ 0         │
│          ┆ ifier(rand ┆ … "2"]     ┆ 0.47],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ om_state=1 ┆            ┆ [0.335,    ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.665],…   ┆            ┆           ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [13]:
print(summary_base)

shape: (34, 8)
┌──────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ model_id ┆ classifier ┆ fold_predi ┆ fold_proba ┆ true_label ┆ validatio ┆ training_ ┆ stacking_ │
│ ---      ┆ ---        ┆ ctions     ┆ bilities   ┆ s          ┆ n_accurac ┆ time_seco ┆ level     │
│ str      ┆ str        ┆ ---        ┆ ---        ┆ ---        ┆ y         ┆ nds       ┆ ---       │
│          ┆            ┆ list[str]  ┆ list[list[ ┆ list[str]  ┆ ---       ┆ ---       ┆ i64       │
│          ┆            ┆            ┆ f64]]      ┆            ┆ f64       ┆ f64       ┆           │
╞══════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ DummyClass ┆ ["1", "1", ┆ [[0.5,     ┆ ["1", "1", ┆ 0.488     ┆ 0.000692  ┆ 0         │
│          ┆ ifier()    ┆ … "1"]     ┆ 0.5],      ┆ … "2"]     ┆           ┆           ┆           │
│          ┆            ┆            ┆ [0.5,      ┆            ┆           ┆           ┆           │
│          ┆            ┆            ┆ 0.5], …    ┆            ┆           ┆           ┆           │
│          ┆            ┆            ┆ [0.…       ┆            ┆           ┆           ┆           │
│ 3        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.470094 ┆ ["1", "1", ┆ 0.524     ┆ 0.068764  ┆ 0         │
│          ┆ ssifierWra ┆ … "2"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ 0.529906], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.4140…   ┆            ┆           ┆           ┆           │
│ 29       ┆ SklearnCla ┆ ["2", "2", ┆ [[0.149336 ┆ ["1", "1", ┆ 0.612     ┆ 0.118009  ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ 0.850664], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.4857…   ┆            ┆           ┆           ┆           │
│ 28       ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1", "1", ┆ 0.628     ┆ 0.113674  ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ [0.48,     ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.52], ……  ┆            ┆           ┆           ┆           │
│ 5        ┆ SklearnCla ┆ ["2", "2", ┆ [[0.15,    ┆ ["1", "1", ┆ 0.636     ┆ 0.11771   ┆ 0         │
│          ┆ ssifierWra ┆ … "1"]     ┆ 0.85],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ pper(class ┆            ┆ [0.38,     ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.62], ……  ┆            ┆           ┆           ┆           │
│ …        ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 8        ┆ MultiRocke ┆ ["2", "2", ┆ [[0.437161 ┆ ["1", "1", ┆ 0.844     ┆ 0.214048  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.562839], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3894…   ┆            ┆           ┆           ┆           │
│ 31       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.451551 ┆ ["1", "1", ┆ 0.856     ┆ 2.459973  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.548449], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3069…   ┆            ┆           ┆           ┆           │
│ 32       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.428505 ┆ ["1", "1", ┆ 0.856     ┆ 2.326782  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.571495], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3080…   ┆            ┆           ┆           ┆           │
│ 30       ┆ MultiRocke ┆ ["2", "2", ┆ [[0.466823 ┆ ["1", "1", ┆ 0.86      ┆ 2.626712  ┆ 0         │
│          ┆ tClassifie ┆ … "1"]     ┆ ,          ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ r(estimato ┆            ┆ 0.533177], ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ [0.3264…   ┆            ┆           ┆           ┆           │
│ 23       ┆ QUANTClass ┆ ["1", "2", ┆ [[0.53,    ┆ ["1", "1", ┆ 0.868     ┆ 1.253702  ┆ 0         │
│          ┆ ifier(rand ┆ … "2"]     ┆ 0.47],     ┆ … "2"]     ┆           ┆           ┆           │
│          ┆ om_state=1 ┆            ┆ [0.335,    ┆            ┆           ┆           ┆           │
│          ┆ …          ┆            ┆ 0.665],…   ┆            ┆           ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [20]:
import polars as pl


# ----------------------------------------------------------------------
# STEP 1 — Load model preds and labels from your Polars DF
# ----------------------------------------------------------------------
def load_models_from_df(df: pl.DataFrame):
    """
    Convert Polars rows into Python objects suitable for ensemble selection.
    """
    models = []
    for row in df.iter_rows(named=True):
        models.append(
            {
                "model_id": row["model_id"],
                "probs": np.array(row["fold_probabilities"], dtype=float),
                "true": np.array(row["true_labels"]),
                "val_acc": row["validation_accuracy"],
            }
        )
    return models


# ----------------------------------------------------------------------
# STEP 2 — Accuracy helper — CORRECT
# ----------------------------------------------------------------------
def accuracy_from_probs(probs: np.ndarray, true_labels: np.ndarray) -> float:
    """
    Convert probabilities to class predictions and compute accuracy.
    Classes are ordinal (sorted unique values).
    """
    # Get sorted unique classes (ordinal order)
    unique_classes = sorted(np.unique(true_labels).astype(int))

    # argmax gives index in probs columns, which maps to sorted unique classes
    pred_indices = probs.argmax(axis=1)  # [0, 1, 0, ...]
    preds = np.array([str(unique_classes[idx]) for idx in pred_indices])

    return (preds == true_labels).mean()


# ----------------------------------------------------------------------
# STEP 3 — Caruana Ensemble Selection
# ----------------------------------------------------------------------
def caruana_ensemble_selection(models, iterations=50):
    """
    Implements the original Caruana et al. (2004/2006) ensemble selection.
    Ensemble uses weighted average of model probabilities.
    """

    # Stack prediction matrices
    preds = np.stack([m["probs"] for m in models])
    true = models[0]["true"]
    n_models = len(models)

    # Step 1: Pick best single model
    accuracies = np.array([accuracy_from_probs(preds[i], true) for i in range(n_models)])

    selected = [accuracies.argmax()]
    ensemble_sum = preds[selected].sum(axis=0)
    best_acc = accuracies[selected[0]]

    print(f"Initial model: {models[selected[0]]['model_id']} acc={best_acc:.4f}")

    # Step 2: Greedy selection with replacement
    for t in range(iterations):
        best_candidate = None
        best_candidate_acc = best_acc

        for i in range(n_models):
            new_sum = ensemble_sum + preds[i]
            new_mean = new_sum / (len(selected) + 1)

            acc = accuracy_from_probs(new_mean, true)

            if acc > best_candidate_acc:
                best_candidate_acc = acc
                best_candidate = i

        if best_candidate is None:
            print(f"Iter {t + 1}: No improvement possible. Stopping.")
            break

        selected.append(best_candidate)
        ensemble_sum += preds[best_candidate]
        best_acc = best_candidate_acc

        print(f"Iter {t + 1}: Added {models[best_candidate]['model_id']} => acc={best_acc:.4f}")

    final_probs = ensemble_sum / len(selected)

    return selected, final_probs, best_acc

In [21]:
# USAGE
# ======================================================================
# Filter to stacking_level == 0 models
summary_base = summary.filter(pl.col("stacking_level") == 0)

models = load_models_from_df(summary_base)

selected, final_probs, final_acc = caruana_ensemble_selection(models, iterations=50)

print("\nSelected model IDs (with repetition):")
print([models[i]["model_id"] for i in selected])

print(f"\nFinal ensemble accuracy: {final_acc:.4f}")
print(f"Ensemble size: {len(selected)} models")

Initial model: 23 acc=0.8680
Iter 1: Added 0 => acc=0.8800
Iter 2: Added 23 => acc=0.8880
Iter 3: No improvement possible. Stopping.

Selected model IDs (with repetition):
['23', '0', '23']

Final ensemble accuracy: 0.8880
Ensemble size: 3 models