In [1]:
import os

os.environ["RAY_DEDUP_LOGS"] = "0"
os.environ["RAY_DISABLE_METRICS"] = "1"
os.environ["RAY_DISABLE_METRICS_EXPORT"] = "1"

In [2]:
import holoviews as hv
import hvplot.polars  # noqa: F401
import polars as pl
from sklearn.metrics import accuracy_score

from autotsc import utils
from autotsc.models import *
from autotsc.utils import *
from autotsc.utils import load_dataset

2025-11-28 21:54:49.325453: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
X_train, y_train, X_test, y_test = load_dataset("CricketZ")
# X_train, y_train, X_test, y_test = load_dataset("MelbournePedestrian")
# X_train, y_train, X_test, y_test = load_dataset("Worms")
# X_train, y_train, X_test, y_test = load_dataset("PhalangesOutlinesCorrect")
X_train, y_train, X_test, y_test = load_dataset("Lightning2")
# X_train, y_train, X_test, y_test = load_dataset("CricketY")
# X_train, y_train, X_test, y_test = load_dataset("OSULeaf")
# X_train, y_train, X_test, y_test = load_dataset("Wine")
# X_train, y_train, X_test, y_test = load_dataset("FiftyWords")
# X_train, y_train, X_test, y_test = load_dataset("Haptics")


# X_train, y_train, X_test, y_test = load_dataset("InlineSkate")
# X_train, y_train, X_test, y_test = load_dataset("SemgHandSubjectCh2")

In [4]:
#

In [5]:
with utils.ray_init_or_reuse(num_cpus=24, resources={"meta": 100}, ignore_reinit_error=True):
    model = AutoTSCModel(verbose=1, n_jobs=-1, n_gpus=-1, model_selection="fast")
    model.fit(X_train, y_train)

2025-11-28 21:55:01,021	INFO worker.py:2023 -- Started a local Ray instance.
/home/gasper_p/workspace/repos/AutoTSC/.venv/lib/python3.12/site-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

|-----------------------|
| Number of samples: 60 |
| Number of channels: 1 |
| Length of series: 637 |
| Number of classes: 2  |
| CPUs: 24/24           |
| GPUs: 2/2             |
| Random seed: 350      |
| Number of folds: 20   |
|-----------------------|

(ray_run_fit_predict_proba_wrapper pid=1991632) 2025-11-28 21:55:14.045016: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=1991632) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=1991642) 2025-11-28 21:55:14.020277: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=1991642) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991640) 2025-11-28 21:55:23.947020: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991640) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991636) 2025-11-28 21:55:24.031050: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991636) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991635) 2025-11-28 21:55:24.201889: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991635) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991634) 2025-11-28 21:55:24.248131: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991634) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991653) 2025-11-28 21:55:24.223710: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991653) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991654) 2025-11-28 21:55:24.628520: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991654) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991633) 2025-11-28 21:55:24.720965: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991633) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991644) 2025-11-28 21:55:24.826298: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991644) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991639) 2025-11-28 21:55:24.941118: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991639) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991638) 2025-11-28 21:55:24.979798: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991638) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991647) 2025-11-28 21:55:25.065353: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991647) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991637) 2025-11-28 21:55:25.049997: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991637) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991646) 2025-11-28 21:55:25.121123: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991646) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991645) 2025-11-28 21:55:25.153508: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991645) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991643) 2025-11-28 21:55:25.338880: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991643) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991651) 2025-11-28 21:55:25.437418: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991651) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1993426) 2025-11-28 21:55:25.492767: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1993426) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1993424) 2025-11-28 21:55:25.625537: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1993424) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991655) 2025-11-28 21:55:25.929661: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991655) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=1991652) 2025-11-28 21:55:26.007816: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=1991652) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(pid=gcs_server) [2025-11-28 21:55:28,197 E 1991337 1991337] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(raylet) [2025-11-28 21:55:30,981 E 1991554 1991554] (raylet) main.cc:979: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=1991642) [2025-11-28 21:55:32,956 E 1991642 1991739] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=1991632) [2025-11-28 21:55:33,643 E 1991632 1991845] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991647) [2025-11-28 21:55:33,675 E 1991647 1991878] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trained base model tab-ridge, OOF accuracy: 0.7500 in 0.01s
Trained base model tab-rf, OOF accuracy: 0.8833 in 0.86s
Trained meta model m-ridgecv, OOF accuracy: 0.8500 in 0.01s

(ray_run_model_on_fold pid=1991637) [2025-11-28 21:55:34,159 E 1991637 1991972] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991639) [2025-11-28 21:55:34,419 E 1991639 1992072] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991640) [2025-11-28 21:55:34,498 E 1991640 1992167] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991635) [2025-11-28 21:55:34,588 E 1991635 1992022] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991650) [2025-11-28 21:55:34,718 E 1991650 1992152] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991646) [2025-11-28 21:55:34,773 E 1991646 1992285] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991633) [2025-11-28 21:55:34,848 E 1991633 1992225] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991645) [2025-11-28 21:55:34,930 E 1991645 1992437] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991648) [2025-11-28 21:55:34,915 E 1991648 1992587] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991651) [2025-11-28 21:55:35,103 E 1991651 1992373] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991643) [2025-11-28 21:55:35,141 E 1991643 1992539] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991634) [2025-11-28 21:55:35,122 E 1991634 1992687] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991644) [2025-11-28 21:55:35,249 E 1991644 1992367] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-28 21:55:35,344 E 1990818 1991631] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991638) [2025-11-28 21:55:35,479 E 1991638 1992967] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991654) [2025-11-28 21:55:35,548 E 1991654 1992738] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991655) [2025-11-28 21:55:35,770 E 1991655 1992920] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991653) [2025-11-28 21:55:35,839 E 1991653 1992867] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991636) [2025-11-28 21:55:35,938 E 1991636 1993019] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1991652) [2025-11-28 21:55:36,024 E 1991652 1992791] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1993426) [2025-11-28 21:55:49,143 E 1993426 1993542] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=1993424) [2025-11-28 21:55:49,418 E 1993424 1993592] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trained meta model m-log, OOF accuracy: 0.8667 in 49.64s

In [6]:
with utils.ray_init_or_reuse(num_cpus=24, resources={"meta": 100}, ignore_reinit_error=True):
    pred = model.predict(X_test)
    print("----- CA", accuracy_score(y_test, pred))

2025-11-28 21:56:33,550	INFO worker.py:2023 -- Started a local Ray instance.

Using best model tab-rf for predictions

(ray_run_predict_proba_wrapper pid=1997703) 2025-11-28 21:56:54.250597: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba_wrapper pid=1997703) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba_wrapper pid=1997695) 2025-11-28 21:56:54.255402: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba_wrapper pid=1997695) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(pid=gcs_server) [2025-11-28 21:57:00,736 E 1997420 1997420] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(raylet) [2025-11-28 21:57:03,499 E 1997613 1997613] (raylet) main.cc:979: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba_wrapper pid=1997695) [2025-11-28 21:57:05,636 E 1997695 1997785] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba_wrapper pid=1997703) [2025-11-28 21:57:05,709 E 1997703 1997835] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997705) [2025-11-28 21:57:05,930 E 1997705 1997900] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997690) [2025-11-28 21:57:06,802 E 1997690 1997977] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997697) [2025-11-28 21:57:07,639 E 1997697 1998051] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997696) [2025-11-28 21:57:07,733 E 1997696 1998146] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997709) [2025-11-28 21:57:07,691 E 1997709 1998084] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997699) [2025-11-28 21:57:08,206 E 1997699 1998232] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997698) 2025-11-28 21:57:08.236676: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997698) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997702) 2025-11-28 21:57:08.329115: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997702) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997691) [2025-11-28 21:57:08,345 E 1997691 1998282] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997712) 2025-11-28 21:57:08.411307: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997712) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997697) 2025-11-28 21:57:08.481094: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997697) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997694) 2025-11-28 21:57:08.457178: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997694) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997706) 2025-11-28 21:57:08.533546: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997706) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997708) [2025-11-28 21:57:08,559 E 1997708 1998371] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997700) [2025-11-28 21:57:08,534 E 1997700 1998360] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997701) 2025-11-28 21:57:08.547421: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997701) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997702) [2025-11-28 21:57:08,773 E 1997702 1998561] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997706) [2025-11-28 21:57:08,737 E 1997706 1998466] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997693) [2025-11-28 21:57:08,809 E 1997693 1998601] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997692) [2025-11-28 21:57:08,809 E 1997692 1998675] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997701) [2025-11-28 21:57:08,791 E 1997701 1998628] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997699) 2025-11-28 21:57:08.890321: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997699) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997710) 2025-11-28 21:57:08.890379: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997710) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997696) 2025-11-28 21:57:09.111184: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997696) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997692) 2025-11-28 21:57:09.092794: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997692) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997704) [2025-11-28 21:57:09,147 E 1997704 1998978] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997710) [2025-11-28 21:57:09,146 E 1997710 1998956] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997712) [2025-11-28 21:57:09,138 E 1997712 1998934] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997713) [2025-11-28 21:57:09,127 E 1997713 1998864] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997694) [2025-11-28 21:57:09,128 E 1997694 1998842] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997698) [2025-11-28 21:57:09,199 E 1997698 1999040] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997707) [2025-11-28 21:57:09,207 E 1997707 1999041] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-28 21:57:09,477 E 1990818 1997689] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997705) 2025-11-28 21:57:09.409271: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997705) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997704) 2025-11-28 21:57:09.408305: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997704) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997711) [2025-11-28 21:57:09,424 E 1997711 1999110] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=1997709) 2025-11-28 21:57:09.808274: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997709) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997690) 2025-11-28 21:57:09.909439: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997690) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997708) 2025-11-28 21:57:09.980679: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997708) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997693) 2025-11-28 21:57:10.038185: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997693) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997713) 2025-11-28 21:57:10.065828: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997713) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997700) 2025-11-28 21:57:10.249938: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997700) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=1997691) 2025-11-28 21:57:10.277681: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=1997691) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Prediction with tab-rf made in 0.07s
Prediction with tab-ridge made in 0.00s
<class 'numpy.ndarray'>
(61, 4)
<class 'numpy.ndarray'>
(61, 4)
----- CA 0.7704918032786885

In [7]:
model2 = RocketClassifier(n_jobs=-1)
model2.fit(X_train, y_train)

RocketClassifier(n_jobs=-1)

In [8]:
pred2 = model2.predict(X_test)
print("----- CA2", accuracy_score(y_test, pred2))

----- CA2 0.7704918032786885

In [9]:
from aeon.classification.hybrid import HIVECOTEV2

model2 = HIVECOTEV2(n_jobs=-1, time_limit_in_minutes=2)
model2.fit(X_train, y_train)

HIVECOTEV2(n_jobs=-1, time_limit_in_minutes=2)

In [10]:
pred2 = model2.predict(X_test)
print("----- CA3", accuracy_score(y_test, pred2))

----- CA3 0.7540983606557377

In [11]:
summary = model.summary()
summary

shape: (4, 5)
┌───────────┬─────────────────────────────────┬─────────────────────┬────────────────┬────────────┐
│ model_id  ┆ model                           ┆ validation_accuracy ┆ stacking_level ┆ train_time │
│ ---       ┆ ---                             ┆ ---                 ┆ ---            ┆ ---        │
│ str       ┆ str                             ┆ f64                 ┆ i64            ┆ f64        │
╞═══════════╪═════════════════════════════════╪═════════════════════╪════════════════╪════════════╡
│ tab-ridge ┆ RayCrossValidationWrapper(mode… ┆ 0.75                ┆ 0              ┆ 0.011929   │
│ tab-rf    ┆ RayCrossValidationWrapper(mode… ┆ 0.883333            ┆ 0              ┆ 0.862428   │
│ m-ridgecv ┆ Ensemble(RidgeClassifierCVWith… ┆ 0.85                ┆ 1              ┆ 0.014122   │
│ m-log     ┆ Ensemble(LogisticRegressionCV(… ┆ 0.866667            ┆ 1              ┆ 49.639019  │
└───────────┴─────────────────────────────────┴─────────────────────┴────────────────┴────────────┘

In [12]:
model.oof_predictions_

shape: (60, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ model_tab-ridge__class ┆ model_tab-ridge__class ┆ model_tab-rf__class_-1 ┆ model_tab-rf__class_1 │
│ _-1                    ┆ _1                     ┆ ---                    ┆ ---                   │
│ ---                    ┆ ---                    ┆ f64                    ┆ f64                   │
│ f64                    ┆ f64                    ┆                        ┆                       │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.446361               ┆ 0.553639               ┆ 0.122                  ┆ 0.878                 │
│ 0.551689               ┆ 0.448311               ┆ 0.93                   ┆ 0.07                  │
│ 0.386448               ┆ 0.613552               ┆ 0.564                  ┆ 0.436                 │
│ 0.252579               ┆ 0.747421               ┆ 0.612                  ┆ 0.388                 │
│ 0.658166               ┆ 0.341834               ┆ 0.172                  ┆ 0.828                 │
│ …                      ┆ …                      ┆ …                      ┆ …                     │
│ 0.476791               ┆ 0.523209               ┆ 0.28                   ┆ 0.72                  │
│ 0.476321               ┆ 0.523679               ┆ 0.132                  ┆ 0.868                 │
│ 0.461319               ┆ 0.538681               ┆ 0.168                  ┆ 0.832                 │
│ 0.444525               ┆ 0.555475               ┆ 0.558                  ┆ 0.442                 │
│ 0.458771               ┆ 0.541229               ┆ 0.582                  ┆ 0.418                 │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [13]:
with utils.ray_init_or_reuse(num_cpus=24, resources={"meta": 100}, ignore_reinit_error=True):
    test_accs = []
    preds = model.predict_per_model(X_test)
    for m, p in preds.items():
        acc = accuracy_score(y_test, p)
        test_accs.append(
            {
                "model_id": m,
                "test_accuracy": acc,
            }
        )
    test_accs = pl.DataFrame(test_accs)
    summary = summary.join(test_accs, on="model_id")

2025-11-28 21:59:49,632	INFO worker.py:2023 -- Started a local Ray instance.
(ray_run_predict_proba_wrapper pid=2012378) 2025-11-28 22:00:04.671533: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba_wrapper pid=2012378) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba_wrapper pid=2012380) 2025-11-28 22:00:04.840032: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba_wrapper pid=2012380) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012361) 2025-11-28 22:00:17.186608: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012361) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012369) 2025-11-28 22:00:17.723360: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012369) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(pid=gcs_server) [2025-11-28 22:00:17,742 E 2012098 2012098] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012372) 2025-11-28 22:00:17.759976: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012372) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012370) 2025-11-28 22:00:18.031589: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012370) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012365) 2025-11-28 22:00:18.575437: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012365) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012362) 2025-11-28 22:00:18.641337: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012362) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012379) 2025-11-28 22:00:18.637336: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012379) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012364) 2025-11-28 22:00:18.897739: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012364) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012375) 2025-11-28 22:00:19.484512: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012375) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012384) 2025-11-28 22:00:19.448024: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012384) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012368) 2025-11-28 22:00:19.572488: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012368) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012366) 2025-11-28 22:00:19.569012: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012366) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012374) 2025-11-28 22:00:19.620633: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012374) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012377) 2025-11-28 22:00:19.568058: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012377) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012373) 2025-11-28 22:00:19.576495: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012373) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(raylet) [2025-11-28 22:00:19,572 E 2012284 2012284] (raylet) main.cc:979: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012371) 2025-11-28 22:00:19.675237: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012371) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012383) 2025-11-28 22:00:19.690024: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012383) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012367) 2025-11-28 22:00:19.929803: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012367) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012382) 2025-11-28 22:00:19.856627: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012382) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=2012376) 2025-11-28 22:00:19.949845: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=2012376) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba_wrapper pid=2012378) [2025-11-28 22:00:22,046 E 2012378 2012493] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba_wrapper pid=2012380) [2025-11-28 22:00:23,025 E 2012380 2012769] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012368) [2025-11-28 22:00:23,045 E 2012368 2012924] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012362) [2025-11-28 22:00:23,041 E 2012362 2012902] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012366) [2025-11-28 22:00:23,042 E 2012366 2012811] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012372) [2025-11-28 22:00:23,051 E 2012372 2012812] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012370) [2025-11-28 22:00:23,054 E 2012370 2012843] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012376) [2025-11-28 22:00:23,028 E 2012376 2012763] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012383) [2025-11-28 22:00:23,177 E 2012383 2013036] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012361) [2025-11-28 22:00:23,180 E 2012361 2013037] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012371) [2025-11-28 22:00:23,224 E 2012371 2013084] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012375) [2025-11-28 22:00:23,258 E 2012375 2013137] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012367) [2025-11-28 22:00:23,379 E 2012367 2013184] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012365) [2025-11-28 22:00:23,449 E 2012365 2013261] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012384) [2025-11-28 22:00:23,661 E 2012384 2013368] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012374) [2025-11-28 22:00:23,621 E 2012374 2013367] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012377) [2025-11-28 22:00:23,682 E 2012377 2013631] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012382) [2025-11-28 22:00:23,682 E 2012382 2013613] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012373) [2025-11-28 22:00:23,666 E 2012373 2013499] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012364) [2025-11-28 22:00:23,682 E 2012364 2013500] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012369) [2025-11-28 22:00:23,664 E 2012369 2013439] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012379) [2025-11-28 22:00:23,862 E 2012379 2013662] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-28 22:00:25,217 E 1990818 2012360] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_predict_proba pid=2012363) [2025-11-28 22:00:25,171 E 2012363 2013804] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Prediction with tab-rf made in 0.13s
Prediction with tab-ridge made in 0.00s
<class 'numpy.ndarray'>
(61, 4)
<class 'numpy.ndarray'>
(61, 4)

In [14]:
pl.Config.set_fmt_str_lengths(500)
for r in summary.sort("validation_accuracy").iter_rows():
    print(r)

('tab-ridge', 'RayCrossValidationWrapper(model=SklearnClassifierWrapper(classifier=RidgeClassifierCVWithProba(alphas=array([1.00000000e-03,4.64158883e-03,2.15443469e-02,1.00000000e-01,4.64158883e-01,2.15443469e+00,1.00000000e+01,4.64158883e+01,2.15443469e+02,1.00000000e+03]))))', 0.75, 0, 0.011928832245757803, 0.6885245901639344)
('m-ridgecv', 'Ensemble(RidgeClassifierCVWithProba(alphas=array([1.00000000e-03,4.64158883e-03,2.15443469e-02,1.00000000e-01,4.64158883e-01,2.15443469e+00,1.00000000e+01,4.64158883e+01,2.15443469e+02,1.00000000e+03])))', 0.85, 1, 0.014121562201762573, 0.7540983606557377)
('m-log', 'Ensemble(LogisticRegressionCV(cv=5,n_jobs=-1))', 0.8666666666666667, 1, 49.63901893929578, 0.7540983606557377)
('tab-rf', 'RayCrossValidationWrapper(model=SklearnClassifierWrapper(classifier=RandomForestClassifier(n_estimators=500,n_jobs=-1)))', 0.8833333333333333, 0, 0.8624281794473063, 0.7704918032786885)

In [15]:
# Create the scatter plot

scatter = summary.hvplot.scatter(
    x="validation_accuracy",
    y="test_accuracy",
    c="stacking_level",
    hover_cols=["model_id", "validation_accuracy", "test_accuracy", "stacking_level"],
    cmap="viridis",
    size=80,
    alpha=0.7,
    title="Validation vs Test Accuracy per Model",
    xlabel="Validation Accuracy",
    ylabel="Test Accuracy",
    width=700,
    height=600,
    grid=True,  # Add grid here
)

# Add text labels for model_id
labels = hv.Labels(
    summary.select(["validation_accuracy", "test_accuracy", "model_id"]).to_pandas(),
    kdims=["validation_accuracy", "test_accuracy"],
    vdims=["model_id"],
).opts(
    text_font_size="8pt",
    text_align="left",
    text_baseline="bottom",
    xoffset=0.0005,  # slight offset so text doesn't overlap point
    yoffset=0.0005,
)

# Add diagonal line
min_val = min(summary["validation_accuracy"].min(), summary["test_accuracy"].min())
max_val = max(summary["validation_accuracy"].max(), summary["test_accuracy"].max())
diagonal = hv.Curve([(min_val, min_val), (max_val, max_val)]).opts(
    color="gray", line_dash="dashed", line_width=1
)

# Combine all
plot = scatter * labels * diagonal
plot

:Overlay
   .Scatter.I :Scatter   [validation_accuracy]   (test_accuracy,stacking_level,model_id)
   .Labels.I  :Labels   [validation_accuracy,test_accuracy]   (model_id)
   .Curve.I   :Curve   [x]   (y)