In [1]:
import os

os.environ["RAY_DEDUP_LOGS"] = "0"
os.environ["RAY_DISABLE_METRICS"] = "1"
os.environ["RAY_DISABLE_METRICS_EXPORT"] = "1"

In [2]:
import holoviews as hv
import polars as pl
from sklearn.metrics import accuracy_score

from autotsc import utils
from autotsc.models import *
from autotsc.utils import *
from autotsc.utils import load_dataset

2025-11-28 09:40:19.174429: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
X_train, y_train, X_test, y_test = load_dataset("CricketZ")
# X_train, y_train, X_test, y_test = load_dataset("MelbournePedestrian")
# X_train, y_train, X_test, y_test = load_dataset("Worms")
# X_train, y_train, X_test, y_test = load_dataset("PhalangesOutlinesCorrect")
# X_train, y_train, X_test, y_test = load_dataset("Lightning2")
# X_train, y_train, X_test, y_test = load_dataset("CricketY")
X_train, y_train, X_test, y_test = load_dataset("OSULeaf")
# X_train, y_train, X_test, y_test = load_dataset("Wine")
# X_train, y_train, X_test, y_test = load_dataset("FiftyWords")
# X_train, y_train, X_test, y_test = load_dataset("Haptics")


# X_train, y_train, X_test, y_test = load_dataset("InlineSkate")
# X_train, y_train, X_test, y_test = load_dataset("SemgHandSubjectCh2")

In [4]:
#

In [5]:
with utils.ray_init_or_reuse(num_cpus=24, resources={"meta": 100}, ignore_reinit_error=True):
    model = AutoTSCModel(model_selection="fast", verbose=1, n_jobs=-1, n_gpus=-1)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print("----- CA", accuracy_score(y_test, pred))

2025-11-28 09:40:23,322	INFO worker.py:2023 -- Started a local Ray instance.
/home/gasper_p/workspace/repos/AutoTSC/.venv/lib/python3.12/site-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

|------------------------|
| Number of samples: 200 |
| Number of channels: 1  |
| Length of series: 427  |
| Number of classes: 6   |
| CPUs: 24/24            |
| GPUs: 2/2              |
| Random seed: 4310      |
| Number of folds: 20    |
|------------------------|

/home/gasper_p/workspace/repos/AutoTSC/.venv/lib/python3.12/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 15 members, which is less than n_splits=20.
  warnings.warn(
(ray_run_fit_predict_proba_wrapper pid=510990) 2025-11-28 09:40:28.150892: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510990) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=510992) 2025-11-28 09:40:28.125821: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510992) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=510995) 2025-11-28 09:40:28.125821: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510995) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=510994) 2025-11-28 09:40:28.141530: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510994) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=510991) 2025-11-28 09:40:28.150887: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510991) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=511001) 2025-11-28 09:40:28.125821: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=511001) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_fit_predict_proba_wrapper pid=510993) 2025-11-28 09:40:28.179600: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_fit_predict_proba_wrapper pid=510993) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510998) 2025-11-28 09:40:33.545968: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510998) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511003) 2025-11-28 09:40:33.535840: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511003) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510997) 2025-11-28 09:40:33.535839: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510997) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511004) 2025-11-28 09:40:33.592007: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511004) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511000) 2025-11-28 09:40:33.535848: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511000) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510989) 2025-11-28 09:40:33.642264: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510989) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511009) 2025-11-28 09:40:33.648825: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511009) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510988) 2025-11-28 09:40:33.642366: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510988) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511006) 2025-11-28 09:40:33.642366: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511006) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510996) 2025-11-28 09:40:33.649044: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510996) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511008) 2025-11-28 09:40:33.795240: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511008) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511011) 2025-11-28 09:40:34.048801: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511011) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512527) 2025-11-28 09:40:35.279205: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512527) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512532) 2025-11-28 09:40:35.326503: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512532) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512530) 2025-11-28 09:40:35.321114: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512530) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512526) 2025-11-28 09:40:35.327722: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512526) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512529) 2025-11-28 09:40:35.576143: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512529) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=510999) 2025-11-28 09:40:40.784894: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=510999) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512525) 2025-11-28 09:40:41.772272: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512525) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511002) 2025-11-28 09:40:41.866219: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511002) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511005) 2025-11-28 09:40:41.983278: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511005) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=512531) 2025-11-28 09:40:42.244967: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=512531) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511010) 2025-11-28 09:40:42.702539: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511010) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_model_on_fold pid=511007) 2025-11-28 09:40:42.874978: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_model_on_fold pid=511007) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(pid=gcs_server) [2025-11-28 09:40:51,948 E 510734 510734] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trained base model tab-ridge, OOF accuracy: 0.4350 in 0.01s
Trained base model tab-rf, OOF accuracy: 0.6250 in 1.12s
Trained base model c22, OOF accuracy: 0.7350 in 0.57s
Trained base model minroc, OOF accuracy: 0.9600 in 0.48s
Trained base model quant, OOF accuracy: 0.6550 in 2.75s
Trained base model hydra, OOF accuracy: 0.9650 in 2.43s
Trained base model roc, OOF accuracy: 0.9350 in 7.91s
Trained meta model m-ridgecv, OOF accuracy: 0.9650 in 0.37s
Trained meta model m-svm, OOF accuracy: 0.9650 in 0.12s

(raylet) [2025-11-28 09:40:53,248 E 510910 510910] (raylet) main.cc:979: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=510990) [2025-11-28 09:40:55,345 E 510990 511470] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=510993) [2025-11-28 09:40:55,344 E 510993 511455] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=510995) [2025-11-28 09:40:55,332 E 510995 511362] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_fit_predict_proba_wrapper pid=511001) [2025-11-28 09:40:55,289 E 511001 511173] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511005) [2025-11-28 09:40:55,367 E 511005 511550] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511002) [2025-11-28 09:40:55,436 E 511002 511829] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=510998) [2025-11-28 09:40:55,422 E 510998 511802] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=510999) [2025-11-28 09:40:55,417 E 510999 511753] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511003) [2025-11-28 09:40:55,399 E 511003 511655] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511006) [2025-11-28 09:40:55,473 E 511006 511880] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511004) [2025-11-28 09:40:55,550 E 511004 512227] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511009) [2025-11-28 09:40:55,549 E 511009 512226] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511000) [2025-11-28 09:40:55,548 E 511000 512191] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511008) [2025-11-28 09:40:55,522 E 511008 512111] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511007) [2025-11-28 09:40:55,520 E 511007 512058] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=510988) [2025-11-28 09:40:55,517 E 510988 512034] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511011) [2025-11-28 09:40:55,494 E 511011 511930] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=511010) [2025-11-28 09:40:55,553 E 511010 512266] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-28 09:40:55,633 E 510527 510987] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512525) [2025-11-28 09:41:01,598 E 512525 512688] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512527) [2025-11-28 09:41:01,604 E 512527 512706] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512532) [2025-11-28 09:41:01,698 E 512532 512912] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512531) [2025-11-28 09:41:01,670 E 512531 512887] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512530) [2025-11-28 09:41:01,654 E 512530 512861] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ray_run_model_on_fold pid=512529) [2025-11-28 09:41:01,772 E 512529 513008] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trained meta model m-log, OOF accuracy: 0.9650 in 15.42s
Using best model m-log for predictions

(ray_run_predict_proba pid=515688) 2025-11-28 09:41:15.460072: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=515688) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(ray_run_predict_proba pid=515694) 2025-11-28 09:41:15.922104: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(ray_run_predict_proba pid=515694) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

----- CA 0.9917355371900827

In [6]:
model2 = RocketClassifier(n_jobs=-1)
model2.fit(X_train, y_train)
pred2 = model2.predict(X_test)
print("----- CA2", accuracy_score(y_test, pred2))

----- CA2 0.9297520661157025

In [7]:
summary = model.summary()
summary

shape: (10, 5)
┌───────────┬─────────────────────────────────┬─────────────────────┬────────────────┬────────────┐
│ model_id  ┆ model                           ┆ validation_accuracy ┆ stacking_level ┆ train_time │
│ ---       ┆ ---                             ┆ ---                 ┆ ---            ┆ ---        │
│ str       ┆ str                             ┆ f64                 ┆ i64            ┆ f64        │
╞═══════════╪═════════════════════════════════╪═════════════════════╪════════════════╪════════════╡
│ tab-ridge ┆ RayCrossValidationWrapper(mode… ┆ 0.435               ┆ 0              ┆ 0.011155   │
│ tab-rf    ┆ RayCrossValidationWrapper(mode… ┆ 0.625               ┆ 0              ┆ 1.117806   │
│ c22       ┆ RayCrossValidationWrapper(mode… ┆ 0.735               ┆ 0              ┆ 0.565915   │
│ minroc    ┆ RayCrossValidationWrapper(mode… ┆ 0.96                ┆ 0              ┆ 0.481398   │
│ quant     ┆ RayCrossValidationWrapper(mode… ┆ 0.655               ┆ 0              ┆ 2.753436   │
│ hydra     ┆ RayCrossValidationWrapper(mode… ┆ 0.965               ┆ 0              ┆ 2.433137   │
│ roc       ┆ RayCrossValidationWrapper(mode… ┆ 0.935               ┆ 0              ┆ 7.911362   │
│ m-ridgecv ┆ Ensemble(RidgeClassifierCVWith… ┆ 0.965               ┆ 1              ┆ 0.36981    │
│ m-svm     ┆ Ensemble(SVC(kernel='linear',p… ┆ 0.965               ┆ 1              ┆ 0.121576   │
│ m-log     ┆ Ensemble(LogisticRegressionCV(… ┆ 0.965               ┆ 1              ┆ 15.419363  │
└───────────┴─────────────────────────────────┴─────────────────────┴────────────────┴────────────┘

In [8]:
model.oof_predictions_

shape: (200, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ model_tab ┆ model_tab ┆ model_tab ┆ model_tab ┆ … ┆ model_roc ┆ model_roc ┆ model_roc ┆ model_ro │
│ -ridge__c ┆ -ridge__c ┆ -ridge__c ┆ -ridge__c ┆   ┆ __class_3 ┆ __class_4 ┆ __class_5 ┆ c__class │
│ lass_1    ┆ lass_2    ┆ lass_3    ┆ lass_4    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ _6       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.176097  ┆ 0.204867  ┆ 0.152621  ┆ 0.181962  ┆ … ┆ 0.105047  ┆ 0.166531  ┆ 0.235932  ┆ 0.235644 │
│ 0.160682  ┆ 0.147281  ┆ 0.1663    ┆ 0.197007  ┆ … ┆ 0.143641  ┆ 0.186237  ┆ 0.220099  ┆ 0.150866 │
│ 0.138855  ┆ 0.171538  ┆ 0.16985   ┆ 0.214154  ┆ … ┆ 0.230526  ┆ 0.176179  ┆ 0.097622  ┆ 0.130941 │
│ 0.254946  ┆ 0.125487  ┆ 0.168916  ┆ 0.201351  ┆ … ┆ 0.140936  ┆ 0.127288  ┆ 0.125587  ┆ 0.128904 │
│ 0.174044  ┆ 0.160428  ┆ 0.14931   ┆ 0.193252  ┆ … ┆ 0.311998  ┆ 0.124176  ┆ 0.129445  ┆ 0.128885 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.250192  ┆ 0.158161  ┆ 0.134352  ┆ 0.181361  ┆ … ┆ 0.100862  ┆ 0.125565  ┆ 0.146133  ┆ 0.126405 │
│ 0.174692  ┆ 0.139271  ┆ 0.149345  ┆ 0.217785  ┆ … ┆ 0.311611  ┆ 0.144145  ┆ 0.18298   ┆ 0.108377 │
│ 0.259002  ┆ 0.133197  ┆ 0.185653  ┆ 0.145246  ┆ … ┆ 0.094569  ┆ 0.132246  ┆ 0.173253  ┆ 0.125342 │
│ 0.179548  ┆ 0.168911  ┆ 0.130934  ┆ 0.230496  ┆ … ┆ 0.129878  ┆ 0.169642  ┆ 0.138038  ┆ 0.121575 │
│ 0.140215  ┆ 0.145834  ┆ 0.251921  ┆ 0.107683  ┆ … ┆ 0.357121  ┆ 0.114938  ┆ 0.139275  ┆ 0.126186 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
with utils.ray_init_or_reuse(num_cpus=24, resources={"meta": 100}, ignore_reinit_error=True):
    test_accs = []
    preds = model.predict_per_model(X_test)
    for m, p in preds.items():
        acc = accuracy_score(y_test, p)
        test_accs.append(
            {
                "model_id": m,
                "test_accuracy": acc,
            }
        )
    test_accs = pl.DataFrame(test_accs)
    summary = summary.join(test_accs, on="model_id")

2025-11-28 09:41:31,964	INFO worker.py:2023 -- Started a local Ray instance.

(autoscaler +1m17s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(autoscaler +1m17s) Error: No available node types can fulfill resource request {'meta': 1.0}. Add suitable node types to this cluster to resolve this issue.

(pid=gcs_server) [2025-11-28 09:42:00,531 E 518382 518382] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(raylet) [2025-11-28 09:42:01,885 E 518551 518551] (raylet) main.cc:979: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518632) [2025-11-28 09:42:03,955 E 518632 519132] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518630) [2025-11-28 09:42:03,955 E 518630 519105] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518645) [2025-11-28 09:42:03,955 E 518645 519096] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518631) [2025-11-28 09:42:03,949 E 518631 518977] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518633) [2025-11-28 09:42:03,932 E 518633 518862] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518635) [2025-11-28 09:42:03,924 E 518635 518812] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518647) [2025-11-28 09:42:03,965 E 518647 519243] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518641) [2025-11-28 09:42:03,975 E 518641 519303] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518638) [2025-11-28 09:42:03,974 E 518638 519281] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518634) [2025-11-28 09:42:03,967 E 518634 519253] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518628) [2025-11-28 09:42:04,065 E 518628 519467] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518636) [2025-11-28 09:42:04,022 E 518636 519409] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518644) [2025-11-28 09:42:04,016 E 518644 519372] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518643) [2025-11-28 09:42:04,016 E 518643 519370] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2025-11-28 09:42:04,419 E 510527 518627] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518639) [2025-11-28 09:42:04,084 E 518639 519538] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518642) [2025-11-28 09:42:04,144 E 518642 519713] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518629) [2025-11-28 09:42:04,132 E 518629 519688] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518640) [2025-11-28 09:42:04,108 E 518640 519638] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518651) [2025-11-28 09:42:04,102 E 518651 519613] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518646) [2025-11-28 09:42:04,188 E 518646 519764] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518650) [2025-11-28 09:42:04,370 E 518650 519814] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518649) [2025-11-28 09:42:04,411 E 518649 519963] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518637) [2025-11-28 09:42:04,405 E 518637 519936] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(pid=518648) [2025-11-28 09:42:04,405 E 518648 519919] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

KeyboardInterrupt:

(autoscaler +1m52s) Error: No available node types can fulfill resource request {'meta': 1.0}. Add suitable node types to this cluster to resolve this issue.

In [ ]:
pl.Config.set_fmt_str_lengths(500)
for r in summary.sort("validation_accuracy").iter_rows():
    print(r)

In [ ]:
# Create the scatter plot

scatter = summary.hvplot.scatter(
    x="validation_accuracy",
    y="test_accuracy",
    c="stacking_level",
    hover_cols=["model_id", "validation_accuracy", "test_accuracy", "stacking_level"],
    cmap="viridis",
    size=80,
    alpha=0.7,
    title="Validation vs Test Accuracy per Model",
    xlabel="Validation Accuracy",
    ylabel="Test Accuracy",
    width=700,
    height=600,
    grid=True,  # Add grid here
)

# Add text labels for model_id
labels = hv.Labels(
    summary.select(["validation_accuracy", "test_accuracy", "model_id"]).to_pandas(),
    kdims=["validation_accuracy", "test_accuracy"],
    vdims=["model_id"],
).opts(
    text_font_size="8pt",
    text_align="left",
    text_baseline="bottom",
    xoffset=0.0005,  # slight offset so text doesn't overlap point
    yoffset=0.0005,
)

# Add diagonal line
min_val = min(summary["validation_accuracy"].min(), summary["test_accuracy"].min())
max_val = max(summary["validation_accuracy"].max(), summary["test_accuracy"].max())
diagonal = hv.Curve([(min_val, min_val), (max_val, max_val)]).opts(
    color="gray", line_dash="dashed", line_width=1
)

# Combine all
plot = scatter * labels * diagonal
plot