In [1]:
import numpy as np
from aeon.classification.interval_based import RSTSF
from sklearn.metrics import accuracy_score
from tscglue.models import LokyStackerV7, LokyStackerV7SoftFilterRidge, TSCGlue, LokyStackerV8Base, LokyStackerV8AutoBestStacking, LokyStackerV8AutoBestBase
from tscglue.old_models import StackerV4, LokyStackerV5, LokyStackerV5SoftRF, LokyStackerV6
from tscglue import utils, data_loader
import polars as pl

In [ ]:
dataset = "Worms"
# dataset = 'Car'
# dataset = 'HandOutlines'
dataset = 'Trace'
X_train, y_train, X_test, y_test = data_loader.load_fold(dataset, 0)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(181, 1, 900) (181,) (77, 1, 900) (77,)

In [3]:
#m = TSCGlue(random_state=492, n_repetitions=1, n_jobs=16, keep_features=True, verbose=2)
#m.fit(X_train, y_train)
#y_pred = m.predict(X_test)

In [4]:
m = LokyStackerV8Base(random_state=492, n_repetitions=1, n_jobs=16, keep_features=True, verbose=2)
m.fit(X_train, y_train)

[0.00s] Starting executor with 16 workers, run_dir=./tscglue_runs/c306521162404ddd
[0.00s] Saved X and y to disk in 0.00s
[0.49s] Computed QUANT features (181, 7987) (11.03 MB) in 0.4836s
[0.54s] Starting repetition 0
[2.51s] Computed MultiRocket features (181, 49728) (68.67 MB) in 1.9707s
[5.03s] Computed Hydra features (181, 7168) (9.90 MB) in 2.5174s
[13.34s] Computed RDST features (181, 30000) (41.43 MB) in 8.3131s
[13.35s] Starting training with 16 workers for 40 models
[15.28s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.9264s for f-2/r-0 (3.06 MB)
[15.35s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.9912s for f-4/r-0 (3.06 MB)
[15.42s] Trained multirockethydra-bestk-p-ridgecv_r0 in 2.0594s for f-0/r-0 (3.06 MB)
[15.44s] Trained multirockethydra-bestk-p-ridgecv_r0 in 2.0780s for f-3/r-0 (3.06 MB)
[15.47s] Trained multirockethydra-bestk-p-ridgecv_r0 in 2.1143s for f-5/r-0 (3.06 MB)
[15.51s] Trained multirockethydra-bestk-p-ridgecv_r0 in 2.1586s for f-1/r-0 (3.06 MB)
[16.48s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.1899s for f-6/r-0 (3.06 MB)
[16.82s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.4697s for f-7/r-0 (3.06 MB)
[16.87s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.4460s for f-8/r-0 (3.06 MB)
[16.91s] Trained multirockethydra-bestk-p-ridgecv_r0 in 1.4641s for f-9/r-0 (3.06 MB)
[16.91s] Completed training for model multirockethydra-bestk-p-ridgecv_r0
[16.91s] OOF acc for model multirockethydra-bestk-p-ridgecv_r0: 0.7569060773480663
[19.02s] Executor shutdown complete

RuntimeError: Worker failed during training quant-etc_r0 fold 0: [Errno 2] No such file or directory: './tscglue_runs/c306521162404ddd/models/quant-etc_r_0_f_0.pkl'

In [ ]:
preds = m.predict_per_model(X_test)
tests_accs = []
for model_name, model_preds in preds.items():
    acc = accuracy_score(y_test, model_preds)
    tests_accs.append({"model": model_name, "test_accuracy": acc})
test_df = pl.DataFrame(tests_accs)

[0.00s] Starting prediction
[0.00s] Starting executor with 16 workers, run_dir=./tscglue_runs/4cdfa4b0e2534157
[3.68s] Computed QUANT features (77, 7987) (2.35 MB) in 3.682947s
[4.11s] Computed repetition 0 MultiRocket features (77, 49728) (14.61 MB) in 0.425264s
[6.58s] Computed repetition 0 Hydra features (77, 7168) (2.11 MB) in 2.473782s
[12.41s] Computed repetition 0 RDST features (77, 30000) (17.62 MB) in 5.823059s
[12.48s] Computed features for prediction
[12.53s] Feature arrays saved to mmap files
[12.53s] Starting prediction with 16 workers for 40 first-level models
[13.23s] Predicted rdst-p-ridgecv_r0 in 0.0448s
[13.24s] Predicted rdst-p-ridgecv_r0 in 0.0646s
[13.28s] Predicted rdst-p-ridgecv_r0 in 0.0663s
[13.28s] Predicted rdst-p-ridgecv_r0 in 0.0705s
[13.29s] Predicted rdst-p-ridgecv_r0 in 0.1023s
[13.30s] Predicted rdst-p-ridgecv_r0 in 0.1208s
[13.30s] Predicted rdst-p-ridgecv_r0 in 0.0726s
[13.35s] Predicted rdst-p-ridgecv_r0 in 0.1023s
[13.37s] Predicted quant-etc_r0 in 0.0511s
[13.38s] Predicted rdst-p-ridgecv_r0 in 0.1175s
[13.38s] Predicted quant-etc_r0 in 0.0407s
[13.40s] Predicted quant-etc_r0 in 0.0269s
[13.43s] Predicted quant-etc_r0 in 0.0310s
[13.44s] Predicted quant-etc_r0 in 0.0326s
[13.45s] Predicted rdst-p-ridgecv_r0 in 0.1761s
[13.45s] Predicted quant-etc_r0 in 0.0376s
[13.46s] Predicted quant-etc_r0 in 0.0467s
[13.49s] Predicted quant-etc_r0 in 0.0303s
[13.49s] Predicted quant-etc_r0 in 0.0513s
[13.50s] Predicted quant-etc_r0 in 0.0366s
[13.62s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1569s
[13.65s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1333s
[13.65s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1730s
[13.66s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1546s
[13.68s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1887s
[13.68s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1555s
[13.75s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1045s
[13.75s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1022s
[13.82s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1703s
[13.83s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.2030s
[43.10s] Predicted rstsf_r0 in 29.8917s
[43.37s] Predicted rstsf_r0 in 30.1662s
[43.99s] Predicted rstsf_r0 in 30.7921s
[44.00s] Predicted rstsf_r0 in 30.8140s
[44.19s] Predicted rstsf_r0 in 30.9852s
[44.20s] Predicted rstsf_r0 in 31.0030s
[44.36s] Predicted rstsf_r0 in 31.1556s
[44.94s] Predicted rstsf_r0 in 31.7513s
[44.96s] Predicted rstsf_r0 in 31.7530s
[45.40s] Predicted rstsf_r0 in 32.2106s
[45.40s] Completed all first-level model predictions
[45.49s] Starting prediction with 16 workers for 10 stacking models
[45.49s] Predicted probability-ridgecv in 0.0021s
[45.49s] Predicted probability-ridgecv in 0.0019s
[45.49s] Predicted probability-ridgecv in 0.0023s
[45.49s] Predicted probability-ridgecv in 0.0013s
[45.50s] Predicted probability-ridgecv in 0.0019s
[45.50s] Predicted probability-ridgecv in 0.0016s
[45.50s] Predicted probability-ridgecv in 0.0017s
[45.50s] Predicted probability-ridgecv in 0.0025s
[45.50s] Predicted probability-ridgecv in 0.0023s
[45.50s] Predicted probability-ridgecv in 0.0019s
[48.31s] Completed all stacking model predictions
[48.41s] Executor shutdown complete

In [ ]:
pl.DataFrame(m.summary())

shape: (5, 3)
┌─────────────────────────────────┬───────┬──────────────┐
│ model                           ┆ level ┆ oof_accuracy │
│ ---                             ┆ ---   ┆ ---          │
│ str                             ┆ i64   ┆ f64          │
╞═════════════════════════════════╪═══════╪══════════════╡
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.756906     │
│ rdst-p-ridgecv_r0               ┆ 0     ┆ 0.729282     │
│ rstsf_r0                        ┆ 0     ┆ 0.712707     │
│ quant-etc_r0                    ┆ 0     ┆ 0.701657     │
│ probability-ridgecv_r0          ┆ 1     ┆ 0.740331     │
└─────────────────────────────────┴───────┴──────────────┘

In [ ]:
pl.DataFrame(m.summary()).join(test_df, on="model").sort("test_accuracy", descending=True)

shape: (4, 4)
┌─────────────────────────────────┬───────┬──────────────┬───────────────┐
│ model                           ┆ level ┆ oof_accuracy ┆ test_accuracy │
│ ---                             ┆ ---   ┆ ---          ┆ ---           │
│ str                             ┆ i64   ┆ f64          ┆ f64           │
╞═════════════════════════════════╪═══════╪══════════════╪═══════════════╡
│ multirockethydra-bestk-p-ridge… ┆ 0     ┆ 0.756906     ┆ 0.805195      │
│ rstsf_r0                        ┆ 0     ┆ 0.712707     ┆ 0.792208      │
│ quant-etc_r0                    ┆ 0     ┆ 0.701657     ┆ 0.779221      │
│ rdst-p-ridgecv_r0               ┆ 0     ┆ 0.729282     ┆ 0.688312      │
└─────────────────────────────────┴───────┴──────────────┴───────────────┘

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

[0.00s] Starting prediction
[0.00s] Starting executor with 16 workers, run_dir=./tscglue_runs/4cdfa4b0e2534157
[3.31s] Computed QUANT features (77, 7987) (2.35 MB) in 3.307783s
[3.73s] Computed repetition 0 MultiRocket features (77, 49728) (14.61 MB) in 0.424854s
[6.49s] Computed repetition 0 Hydra features (77, 7168) (2.11 MB) in 2.753385s
[12.12s] Computed repetition 0 RDST features (77, 30000) (17.62 MB) in 5.638013s
[12.25s] Computed features for prediction
[12.28s] Feature arrays saved to mmap files
[12.28s] Starting prediction with 16 workers for 40 first-level models
[15.70s] Predicted rdst-p-ridgecv_r0 in 0.0460s
[15.74s] Predicted rdst-p-ridgecv_r0 in 0.0787s
[15.76s] Predicted rdst-p-ridgecv_r0 in 0.0780s
[15.76s] Predicted rdst-p-ridgecv_r0 in 0.0954s
[15.76s] Predicted rdst-p-ridgecv_r0 in 0.0517s
[15.78s] Predicted rdst-p-ridgecv_r0 in 0.1230s
[15.79s] Predicted rdst-p-ridgecv_r0 in 0.1353s
[15.81s] Predicted quant-etc_r0 in 0.0264s
[15.85s] Predicted rdst-p-ridgecv_r0 in 0.0937s
[15.86s] Predicted quant-etc_r0 in 0.0255s
[15.87s] Predicted quant-etc_r0 in 0.0576s
[15.89s] Predicted rdst-p-ridgecv_r0 in 0.1148s
[15.89s] Predicted quant-etc_r0 in 0.0255s
[15.92s] Predicted quant-etc_r0 in 0.0323s
[15.92s] Predicted quant-etc_r0 in 0.0320s
[15.93s] Predicted quant-etc_r0 in 0.0241s
[15.94s] Predicted quant-etc_r0 in 0.0488s
[15.96s] Predicted rdst-p-ridgecv_r0 in 0.1652s
[15.98s] Predicted quant-etc_r0 in 0.0489s
[15.99s] Predicted quant-etc_r0 in 0.0456s
[16.11s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1870s
[16.16s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.2047s
[16.16s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.2046s
[16.17s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1540s
[16.18s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.2154s
[16.27s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1479s
[16.32s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.3299s
[16.35s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1733s
[16.37s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.1813s
[16.42s] Predicted multirockethydra-bestk-p-ridgecv_r0 in 0.2278s
[49.47s] Predicted rstsf_r0 in 33.8214s
[49.81s] Predicted rstsf_r0 in 34.1176s
[49.92s] Predicted rstsf_r0 in 34.2448s
[50.01s] Predicted rstsf_r0 in 34.3549s
[50.04s] Predicted rstsf_r0 in 34.3821s
[50.12s] Predicted rstsf_r0 in 34.4609s
[50.16s] Predicted rstsf_r0 in 34.4765s
[50.30s] Predicted rstsf_r0 in 34.6225s
[50.71s] Predicted rstsf_r0 in 35.0189s
[50.75s] Predicted rstsf_r0 in 35.0697s
[50.75s] Completed all first-level model predictions
[50.86s] Starting prediction with 16 workers for 10 stacking models
[50.87s] Predicted probability-ridgecv in 0.0025s
[50.87s] Predicted probability-ridgecv in 0.0026s
[50.87s] Predicted probability-ridgecv in 0.0021s
[50.87s] Predicted probability-ridgecv in 0.0018s
[50.88s] Predicted probability-ridgecv in 0.0021s
[50.88s] Predicted probability-ridgecv in 0.0021s
[50.88s] Predicted probability-ridgecv in 0.0019s
[50.88s] Predicted probability-ridgecv in 0.0050s
[50.88s] Predicted probability-ridgecv in 0.0058s
[50.90s] Predicted probability-ridgecv in 0.0221s
[54.04s] Completed all stacking model predictions
[54.13s] Executor shutdown complete
Accuracy on Worms: 0.8181818181818182

In [ ]:
F = m.get_features()
F.estimated_size('gb')

0.12795495241880417

In [ ]:
P = m.get_oof_predictions()
P.estimated_size('gb')

3.371387720108032e-05

In [ ]:
m = LokyStackerV6(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

[0.0000s] Starting fitting
Starting executor with 16 workers, run_dir=./tscglue_runs/3db5077ed32b4ba6
[2.7946s] Computed QUANT features (181, 7987) (11.03 MB) in 2.7905s
[2.7976s] Starting repetition 0
[4.3008s] Computed MultiRocket features (181, 49728) (68.67 MB) in 1.5031s
[8.0955s] Computed Hydra features (181, 7168) (9.90 MB) in 3.7942s
[23.6057s] Computed RDST features (181, 30000) (41.43 MB) in 15.5099s
[23.6111s] Starting training with 16 workers for 40 models

Process SpawnProcess-62:
Process SpawnProcess-51:
Process SpawnProcess-49:
Process SpawnProcess-61:
Process SpawnProcess-64:
Process SpawnProcess-57:
Process SpawnProcess-60:
Process SpawnProcess-53:
Process SpawnProcess-52:
Process SpawnProcess-55:
Process SpawnProcess-58:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 7, in <module>
    from aeon.classification.convolution_based import (
    ...<5 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/__init__.py", line 12, in <module>
    from aeon.classification.convolution_based._arsenal import Arsenal
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/_arsenal.py", line 20, in <module>
    from aeon.transformations.collection.convolution_based import (
    ...<3 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/__init__.py", line 10, in <module>
    from ._hydra import HydraTransformer
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/_hydra.py", line 130, in <module>
    if _check_soft_dependencies("torch", severity="none"):
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/utils/validation/_dependencies.py", line 115, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/__init__.py", line 2785, in <module>
    from torch import _meta_registrations
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 51, in <module>
    _meta_lib_dont_use_me_use_register_meta = torch.library.Library("aten", "IMPL", "Meta")
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/library.py", line 101, in __init__
    self.m: Any | None = torch._C._dispatch_library(
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        kind, ns, dispatch_key, filename, lineno
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 7, in <module>
    from aeon.classification.convolution_based import (
    ...<5 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/__init__.py", line 12, in <module>
    from aeon.classification.convolution_based._arsenal import Arsenal
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/_arsenal.py", line 20, in <module>
    from aeon.transformations.collection.convolution_based import (
    ...<3 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/__init__.py", line 10, in <module>
    from ._hydra import HydraTransformer
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/_hydra.py", line 130, in <module>
    if _check_soft_dependencies("torch", severity="none"):
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/utils/validation/_dependencies.py", line 115, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 7, in <module>
    from aeon.classification.convolution_based import (
    ...<5 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/__init__.py", line 12, in <module>
    from aeon.classification.convolution_based._arsenal import Arsenal
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/_arsenal.py", line 20, in <module>
    from aeon.transformations.collection.convolution_based import (
    ...<3 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/__init__.py", line 10, in <module>
    from ._hydra import HydraTransformer
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/_hydra.py", line 130, in <module>
    if _check_soft_dependencies("torch", severity="none"):
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/utils/validation/_dependencies.py", line 115, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/__init__.py", line 2785, in <module>
    from torch import _meta_registrations
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 8456, in <module>
    activate_meta()
    ~~~~~~~~~~~~~^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 8453, in activate_meta
    _meta_lib_dont_use_me_use_register_meta.impl(op_overload, fn)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/library.py", line 326, in impl
    key = self.ns + "/" + name.split("::")[-1] + "/" + dispatch_key
                          ~~~~~~~~~~^^^^^^
KeyboardInterrupt
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/__init__.py", line 2785, in <module>
    from torch import _meta_registrations
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 3217, in <module>
    @register_meta(aten.adaptive_max_pool2d)
     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 71, in wrapper
    pytree.tree_map_(register, op)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 7, in <module>
    from aeon.classification.convolution_based import (
    ...<5 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/__init__.py", line 12, in <module>
    from aeon.classification.convolution_based._arsenal import Arsenal
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/_arsenal.py", line 20, in <module>
    from aeon.transformations.collection.convolution_based import (
    ...<3 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/__init__.py", line 10, in <module>
    from ._hydra import HydraTransformer
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/_hydra.py", line 130, in <module>
    if _check_soft_dependencies("torch", severity="none"):
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/utils/validation/_dependencies.py", line 115, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/__init__.py", line 2785, in <module>
    from torch import _meta_registrations
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 8456, in <module>
    activate_meta()
    ~~~~~~~~~~~~~^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 8410, in activate_meta
    if torch._C._dispatch_has_kernel_for_dispatch_key(
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        op_overload.name(), "CompositeImplicitAutograd"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/utils/_pytree.py", line 1569, in tree_map_
    deque(map(func, *flat_args), maxlen=0)  # consume and exhaust the iterable
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 69, in register
    _add_op_to_registry(meta_table, op, fn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_decomp/__init__.py", line 89, in _add_op_to_registry
    if torch._C._dispatch_has_kernel(op_overload.name()):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 7, in <module>
    from aeon.classification.convolution_based import (
    ...<5 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/__init__.py", line 12, in <module>
    from aeon.classification.convolution_based._arsenal import Arsenal
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/convolution_based/_arsenal.py", line 20, in <module>
    from aeon.transformations.collection.convolution_based import (
    ...<3 lines>...
    )
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/__init__.py", line 10, in <module>
    from ._hydra import HydraTransformer
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/convolution_based/_hydra.py", line 130, in <module>
    if _check_soft_dependencies("torch", severity="none"):
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/utils/validation/_dependencies.py", line 115, in _check_soft_dependencies
    pkg_ref = import_module(package_import_name)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/__init__.py", line 2785, in <module>
    from torch import _meta_registrations
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 1051, in <module>
    @register_meta(aten.cholesky_solve)
     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 71, in wrapper
    pytree.tree_map_(register, op)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/utils/_pytree.py", line 1569, in tree_map_
    deque(map(func, *flat_args), maxlen=0)  # consume and exhaust the iterable
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_meta_registrations.py", line 69, in register
    _add_op_to_registry(meta_table, op, fn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/torch/_decomp/__init__.py", line 89, in _add_op_to_registry
    if torch._C._dispatch_has_kernel(op_overload.name()):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/concurrent/futures/process.py", line 242, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/petelin/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/multiprocessing/queues.py", line 120, in get
    return _ForkingPickler.loads(res)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/petelin/TSCGlue/tscglue/old_models.py", line 14, in <module>
    from aeon.classification.dictionary_based import WEASEL_V2, ContractableBOSS
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/dictionary_based/__init__.py", line 17, in <module>
    from aeon.classification.dictionary_based._boss import BOSSEnsemble, IndividualBOSS
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/classification/dictionary_based/_boss.py", line 22, in <module>
    from aeon.transformations.collection.dictionary_based import SFAFast
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/dictionary_based/__init__.py", line 9, in <module>
    from aeon.transformations.collection.dictionary_based._sfa_fast import SFAFast
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/aeon/transformations/collection/dictionary_based/_sfa_fast.py", line 804, in <module>
    @njit(fastmath=True, cache=True)
     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/numba/core/decorators.py", line 225, in wrapper
    disp.enable_caching()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/numba/core/dispatcher.py", line 807, in enable_caching
    self._cache = FunctionCache(self.py_func)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/numba/core/caching.py", line 647, in __init__
    self._impl = self._impl_class(py_func)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/petelin/TSCGlue/.venv/lib/python3.13/site-packages/numba/core/caching.py", line 379, in __init__
    locator = cls.from_function(py_func, source_path)

Executor shutdown complete

KeyboardInterrupt:

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")

In [ ]:
m = LokyStackerV5(random_state=492, n_repetitions=1, n_jobs=16)
m.fit(X_train, y_train)

In [ ]:
y_pred = m.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy on {dataset}: {acc}")